name: iclstm-repro
channels:
  - conda-forge
dependencies:
  - python=3.11.3
  - pip
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.10.1
  - scikit-learn=1.3.2
  - matplotlib=3.7.3
  - ipykernel=6.25.2
  - ipython=8.12.3
  - ipyopt=0.12.10
  - pip:
      - tensorflow-macos==2.13.0
      - tensorflow-metal==1.0.1
      - keras==2.13.1
